source "https://rubygems.org"

gem "rails", "~> 8.0.2"

gem "puma", ">= 5.0"

gem "sqlite3", ">= 2.1"
gem "pg", ">= 1.6"
gem "rack-cors"
gem "redis", ">= 5.0"
gem "connection_pool", ">= 2.2.5"
gem "bootsnap", require: false
gem "thruster", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 8.0"
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
end
