source "https://rubygems.org"

gem "rails", "~> 8.0.2"

gem "puma", ">= 5.0"

gem "sqlite3", ">= 2.1"
gem "pg", ">= 1.6"
gem "rack-cors"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 8.0"
end
