default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "questboard") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "questboard") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "questboard_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "questboard_test") %>

production:
  <<: *default
  url: <%= Rails.env.production? ? ENV.fetch("DATABASE_URL") : ENV.fetch("DATABASE_URL", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
